version: '3.8'

services:
  django-cast:
    image: ghcr.io/remotephone/django-cast:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.casts-http.rule=Host(`casts.my.domain`)
        - traefik.http.routers.casts-http.entrypoints=http
        - traefik.http.routers.casts-http.middlewares=https-redirect
        - traefik.http.routers.casts-https.rule=Host(`casts.my.domain`)
        - traefik.http.routers.casts-https.entrypoints=https
        - traefik.http.routers.casts-https.tls=true
        - traefik.http.routers.casts-https.tls.certresolver=le
        - traefik.http.services.casts.loadbalancer.server.port=8000
      replicas: 1
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
